kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggers-minimal
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggers-minimal-ci
rules:
# EventListeners need to be able to fetch any clustertriggerbindings
- apiGroups: ["triggers.tekton.dev"]
  resources: ["clustertriggerbindings"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-ci-workspace-listener
secrets:
- name: ci-webhook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-ci-jobs
secrets:
- name: ci-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-ci-workspace-listener-triggers-minimal
subjects:
- kind: ServiceAccount
  name: tekton-ci-workspace-listener
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: triggers-minimal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-ci-jobs-triggers-minimal
subjects:
- kind: ServiceAccount
  name: tekton-ci-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: triggers-minimal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-ci-workspace-listener-triggers-minimal-ci
subjects:
- kind: ServiceAccount
  name: tekton-ci-workspace-listener
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: triggers-minimal
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-map-admin
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-config-map-admin
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-map-admin
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-ci-jobs-triggers
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers", "clustertriggerbindings"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-ci-jobs-triggers-tekton-ci-workspace-listener
subjects:
- kind: ServiceAccount
  name: tekton-ci-workspace-listener
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-ci-jobs-triggers
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer2default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "deployments/scale"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-deployer2default
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer2default